src/main/java/com/whiskey/rvcom/repository/ReviewCommentRepository.java
src/main/java/com/whiskey/rvcom/repository/ReviewImageRepository.java
src/main/java/com/whiskey/rvcom/repository/ReviewRepository.java

- 리뷰
- 리뷰이미지(매핑테이블)
- 리뷰댓글
이상 3개종 엔티티에 대응하는 리포지토리 모듈 추가

feat(review): 리뷰 관련 엔티티 3종 jpa 리포지토리 모듈 추가 #85

---

src/main/java/com/whiskey/rvcom/entity/repository/RestaurantReportRepository.java
src/main/java/com/whiskey/rvcom/entity/repository/ReviewCommentReportRepository.java
src/main/java/com/whiskey/rvcom/entity/repository/ReviewReportRepository.java

- ReviewReportRepository (리뷰신고)
- ReviewCommentRepository (리뷰 댓글신고)
- RestrauntReportRepository (식당신고)

feat(report): 신고 엔티티 매핑을 위한 jap 레포지토리 3개 추가 #86

---

src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java
src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java

feat: 리포지토리 모듈 추가 #88

---

build.gradle
src/main/java/com/whiskey/rvcom/config/AppConfig.java
src/main/java/com/whiskey/rvcom/repository/RestaurantReportRepository.java
src/main/java/com/whiskey/rvcom/repository/ReviewCommentReportRepository.java
src/main/java/com/whiskey/rvcom/repository/ReviewReportRepository.java

ModelMapper 사용을 위한 의존성 주입
에 더해서 제가 repository 잘못된 위치에 생성해서 수정했습니다.

Feat(modelmapperregist): ModelMapper 사용을 위한 의존성 주입 + report의 repository 위치 수정

---

src/main/java/repository/MemberRepository.java

feat: 회원 Repository 생성 #83

---

src/main/java/com/whiskey/rvcom/entity/favorite/Favorite.java
src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiry.java
src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiryResponse.java
src/main/java/com/whiskey/rvcom/entity/member/Member.java
src/main/java/com/whiskey/rvcom/entity/report/Report.java
src/main/java/com/whiskey/rvcom/entity/report/RestaurantReport.java
src/main/java/com/whiskey/rvcom/entity/report/ReviewCommentReport.java
src/main/java/com/whiskey/rvcom/entity/report/ReviewReport.java
src/main/java/com/whiskey/rvcom/entity/resource/ImageFile.java
src/main/java/com/whiskey/rvcom/entity/restaurant/Address.java
src/main/java/com/whiskey/rvcom/entity/restaurant/OpenCloseTime.java
src/main/java/com/whiskey/rvcom/entity/restaurant/Restaurant.java
src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantNotice.java
src/main/java/com/whiskey/rvcom/entity/restaurant/WeeklyOpenCloseTime.java
src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java
src/main/java/com/whiskey/rvcom/entity/restaurant/registration/RestaurantRegistrationApplication.java
src/main/java/com/whiskey/rvcom/entity/review/Review.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewComment.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewImage.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewLike.java

Lombok
@Getter / @Setter 어노테이션 배당

엔티티 매퍼 객체에 프로퍼티 속성 부여

---

src/main/java/com/whiskey/rvcom/repository/RestaurantInquiryRepository.java

- 한 음식점에 해당하는 문의 내역 조회하는 쿼리메서드 작성

feat: 쿼리메서드 작성

---

src/main/java/com/whiskey/rvcom/repository/FavoriteRepository.java

- FavoriteRepository.java:
- 특정 회원의 즐겨찾기 목록을 조회하는 메소드 추가
- 특정 회원의 특정 음식점 즐겨찾기 여부를 확인하는 메소드 추가
- 특정 회원의 특정 음식점 즐겨찾기를 삭제하는 메소드 추가
리뷰 부ㅜ탁드려ㅑ요

Feat/favorite -> devel 브랜치 머지 

---

src/main/java/com/whiskey/rvcom/config/AppConfig.java
src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantDTO.java
src/main/java/com/whiskey/rvcom/report/model/dto/RestaurantReportDTO.java
src/main/java/com/whiskey/rvcom/report/model/dto/ReviewCommentReportDTO.java
src/main/java/com/whiskey/rvcom/report/model/dto/ReviewReportDTO.java
src/main/java/com/whiskey/rvcom/report/service/ReportService.java
src/main/resources/templates/restaurantDetail.html
src/test/java/com/whiskey/rvcom/ReportTest.java

- 식당 신고 전체 조회 메서드 구현
- 기능 구현 관련 필요 DTO 생성
- Report Test 진행을 위한 Test 클래스 생성

feat(Report): 식당신고목록 전체조회 메서드

---

src/main/java/com/whiskey/rvcom/repository/MemberRepository.java

feat: 멤버 레포 메소드 추가 #83

---

src/main/java/com/whiskey/rvcom/report/model/dto/ReviewCommentReportDTO.java
src/main/java/com/whiskey/rvcom/report/model/dto/ReviewReportDTO.java
src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
src/main/java/com/whiskey/rvcom/review/dto/ReviewCommentDTO.java
src/main/java/com/whiskey/rvcom/review/dto/ReviewDTO.java
src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java
src/test/java/com/whiskey/rvcom/review/ReviewServiceTest.java

- testcode에 최소한의 단정문 사용
- ReviewDTO 위치 이동
- 댓글 리뷰 신고 등록 기능 구현
- ReviewCommentDTO 위치 이동

fix(Report): 피드백 반영 완료입니다.

---

src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java

- 1개 조회 후 상태값 변경을 위한 로직에 필요해서 만들었습니다.

feat(report): 신고 처리 로직을 위한 신고 1개만 조회하기 #140

---

src/main/resources/static/js/kakaoMapDetailView.js
src/main/resources/templates/restaurantDetail.html

추후 controller로부터 음식접의 주소를 전달받아 위치를 표시하는 기능이 필요함

feat: 음식점 상세 조회 페이지에서 해당 음식점의 위치를 확인할 수 있도록 지도 표시 기능 구현

---

src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
src/test/java/com/whiskey/rvcom/report/RestaurantReportTest.java
src/test/java/com/whiskey/rvcom/report/ReviewCommentReportTest.java
src/test/java/com/whiskey/rvcom/report/ReviewReportTest.java

+ 객체 매개변수가 필요하지 않은 상황에서 사용된 변수 일반 변수로 변경

refactor(report): 코드 정리 commit 입니다.

---

src/main/resources/static/css/searchResults.css
src/main/resources/static/js/searchResults.js
src/main/resources/templates/searchResults.html

- searchResults.css:
- 색상 팔레트 변수 정의로 일관된 스타일 적용
- 검색 배너 레이아웃 개선 및 중앙 정렬
- 지도 컨테이너 크기 및 위치 조정
- 결과 카드 호버 효과 추가
- 반응형 디자인을 위한 미디어 쿼리 구현
- 전반적인 스타일 최적화 및 정리
- searchResults.js:
- 결과 카드에 JavaScript 호버 효과 추가
- searchResults.html:
- 검색 결과 페이지 body에 클래스 추가
TODO:
지도 부분 고정 해야할듯..?

feat(search-results): 검색 결과 페이지 UI 개선 및 반응형 디자인 구현

---

src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantNotice.java
src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
src/main/java/com/whiskey/rvcom/notice/dto/RestaurantNoticeRequestDTO.java
src/main/java/com/whiskey/rvcom/notice/dto/RestaurantNoticeResponseDTO.java
src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java
src/test/java/com/whiskey/rvcom/notice/RestaurantNoticeServiceTest.java

- 공지사항 조회, 작성 로직 구현
- RestaurantNotice 클래스에 생성자 추가
- 요청 및 응답 객체 담을 DTO 클래스 생성
- RestaurantNoticeRepository에 메서드 추가
- 테스트 코드 작성

feat: 음식점 공지사항 조회 및 작성 기능 구현 (#169, #170)

---

src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiry.java
src/main/java/com/whiskey/rvcom/entity/inquiry/restaurant/RestaurantInquiryReply.java
src/main/java/com/whiskey/rvcom/entity/restaurant/RestaurantNotice.java
src/main/java/com/whiskey/rvcom/entity/review/Review.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewComment.java
src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java
src/test/java/com/whiskey/rvcom/notice/RestaurantNoticeServiceTest.java

추가로 음식점 공지사항 삭제 여부 및 삭제 시간 컬럼 추가하고 작성일, 삭제일 주석 전부 변경했습니다

feat: 음식점 공지사항 삭제 기능 구현 #182

---

build/resources/main/templates/main.html
src/main/java/com/whiskey/rvcom/misc/TestController.java
src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
src/main/java/com/whiskey/rvcom/report/controller/RegistReportController.java
src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
src/main/java/com/whiskey/rvcom/review/dto/ReviewDTO.java
src/main/resources/static/js/restaurantDetail.js
src/main/resources/templates/adminMain.html
src/main/resources/templates/adminReport.html
src/main/resources/templates/fragments/adminHeader.html
src/main/resources/templates/fragments/adminSideBar.html
src/main/resources/templates/fragments/reviewItem.html
src/main/resources/templates/main.html
src/main/resources/templates/report/restaurantReport.html
src/main/resources/templates/restaurantDetail.html

ui/ux + feat(report): 식당 신고 메서드 수정

---

build/resources/main/templates/main.html
src/main/java/com/whiskey/rvcom/controller/OwnerFragmentController.java
src/main/java/com/whiskey/rvcom/misc/TestController.java
src/main/resources/static/css/owner-dashboard.css
src/main/resources/static/js/owner-dashboard.js
src/main/resources/static/js/restaurant-info.js
src/main/resources/templates/fragments/owner/dashboard.html
src/main/resources/templates/fragments/owner/inquiries.html
src/main/resources/templates/fragments/owner/menu-management.html
src/main/resources/templates/fragments/owner/notices.html
src/main/resources/templates/fragments/owner/restaurant-info.html
src/main/resources/templates/main.html
src/main/resources/templates/owner/dashboard.html

이 PR은 점주 관리자 대시보드의 기능 구현과 UI 개선을 포함합니다. 주요 변경 사항은 다음과 같습니다:
1. 점주 관리자 대시보드 UI 추가 (#186)
2. 점주 대시보드 UI 개선 및 컨텐츠 업데이트
3. 점주 대시보드 다크 테마 적용 (#186)
4. 점주 대시보드 동적 콘텐츠 로딩 구현 (#186)
5. 점주 대시보드 JavaScript 기능 개선 (#186)
6. 점주 음식점 정보 관리 기능 구현 (#187)
- `main.html`에 점주 관리자 대시보드 링크 추가
- `TestController`에 점주 대시보드 페이지 라우팅 추가
- 점주 대시보드 UI 구현 (`dashboard.html`)
- 대시보드용 CSS 스타일 추가 (`owner-dashboard.css`)
- 사이드바 로고 텍스트를 'FoodFolio'로 변경
- 대시보드 카드 내용 업데이트: '오늘의 예약' 제거, '평균 평점' 카드 추가
- 최근 리뷰 섹션 추가
- 전체적인 색상 스키마를 다크 테마로 변경
- FoodFolio 로고 스타일 추가
- 버튼, 테이블 등 추가 요소들의 스타일 정의
- `OwnerFragmentController.java`: 점주 대시보드 프래그먼트 요청을 처리하는 컨트롤러 추가
- `owner-dashboard.js`: AJAX를 통한 동적 콘텐츠 로딩 구현, 페이지 타이틀 동적 업데이트 기능 추가
- `fragments/owner/`: 대시보드, 음식점 정보, 문의 내역, 공지사항, 메뉴 관리 프래그먼트 파일 추가
- …

Uiux/owner -> devel 점주 관리자 대시보드 기능 구현 및 UI 개선

---

build/resources/main/templates/main.html
src/main/resources/static/css/owner-dashboard.css
src/main/resources/static/css/restaurantDetail.css
src/main/resources/static/js/menu-management.js
src/main/resources/static/js/owner-dashboard.js
src/main/resources/templates/fragments/owner/menu-management.html
src/main/resources/templates/owner/dashboard.html

- 점주 대시보드에 메뉴 관리 기능을 추가했습니다.
- 메뉴 목록 조회, 추가, 수정, 삭제 기능 등 백엔드를 위한 공간을 마련했습니다.
- 페이지네이션을 통해 메뉴 목록을 효율적으로 표시합니다.
1. `src/main/resources/static/css/owner-dashboard.css`
- 메뉴 관리 페이지 스타일 추가
- 카드 호버 효과, 모달 스타일 등 구현
2. `src/main/resources/static/js/menu-management.js`
- 메뉴 관리 기능 초기화 및 CRUD 작업 구현
- 페이지네이션 기능 추가
- 메뉴 추가/수정을 위한 모달 기능 구현
3. `src/main/resources/static/js/owner-dashboard.js`
- 메뉴 관리 초기화 함수 추가
4. `src/main/resources/templates/fragments/owner/menu-management.html`
- 메뉴 관리 UI 구현
- 메뉴 목록 표시 및 페이지네이션 구조 추가
- 메뉴 추가/수정 모달 구현
5. `src/main/resources/templates/owner/dashboard.html`
- 메뉴 관리 관련 JavaScript 파일 추가
- 현재는 더미 데이터를 사용하고 있습니다. 백엔드 API 연동 작업이 필요합니다.

feat(owner): 점주 대시보드 메뉴 관리 기능 구현 #193

---

build/resources/main/templates/main.html
src/main/java/com/whiskey/rvcom/report/controller/ReportController.java
src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
src/main/resources/templates/adminMain.html
src/main/resources/templates/adminReport.html
src/main/resources/templates/report/restaurantDetail.html
src/main/resources/templates/report/restaurantReport.html

- UI/UX 임시로 해놓고 전체 목록 불러오는 기능 완성입니다.
+ detail 구상 중 길을 잃어서 체크포인트 겸 저장용 commit 입니다.

Feat(report) : 식당 신고 전체 조회 웹연동2 #189

---

src/main/resources/static/css/restaurantDetail.css
src/main/resources/static/css/restaurantDetail/info.css
src/main/resources/static/css/restaurantDetail/inquiries.css
src/main/resources/static/css/restaurantDetail/notices.css
src/main/resources/static/css/restaurantDetail/reviews.css
src/main/resources/static/js/restaurantDetail.js
src/main/resources/static/js/restaurantDetail/info.js
src/main/resources/static/js/restaurantDetail/inquiries.js
src/main/resources/static/js/restaurantDetail/notices.js
src/main/resources/static/js/restaurantDetail/reviews.js
src/main/resources/templates/fragments/modal.html
src/main/resources/templates/fragments/restaurantDetail/info.html
src/main/resources/templates/fragments/restaurantDetail/inquiries.html
src/main/resources/templates/fragments/restaurantDetail/notices.html
src/main/resources/templates/fragments/restaurantDetail/reviews.html
src/main/resources/templates/restaurantDetail.html

이 PR은 음식점 상세 페이지의 전반적인 구조를 개선하고, 코드의 모듈화 및 새로운 기능을 추가하는 작업을 포함합니다.
1. HTML 구조 개선 및 모듈화
2. JavaScript 코드 모듈화 및 기능 확장
3. CSS 구조 개선 및 새로운 스타일 파일 추가
4. 전반적인 코드 리팩토링 및 최적화
- `modal.html`: 모달 구조 개선 및 스타일 변경
- `restaurantDetail.html`: 각 탭 내용을 분리된 파일로 대체
- 새로운 HTML 파일 추가:
- `restaurantDetail/info.html`
- `restaurantDetail/inquiries.html`
- `restaurantDetail/notices.html`
- `restaurantDetail/reviews.html`
- `restaurantDetail.js`: 전역 객체 생성 및 공통 기능 구현
- 새로운 JavaScript 파일 추가:
- `restaurantDetail/info.js`
- `restaurantDetail/inquiries.js`
- `restaurantDetail/notices.js`
- `restaurantDetail/reviews.js`
- `restaurantDetail.css`: 스타일 최적화 및 중복 코드 정리
- 새로운 CSS 파일 추가:
- `restaurantDetail/info.css`
- `restaurantDetail/inquiries.css`
- `restaurantDetail/notices.css`
- `restaurantDetail/reviews.css`
1. 각 탭(정보, …

(Uiux/refactor)음식점 상세 페이지 리팩토링 및 기능 개선

---

src/main/resources/templates/fragments/restaurantCard.html

- restaurantCard.html:
- 상세 정보 버튼의 텍스트를 "상세 정보 / 주문"에서 "상세 정보"로 변경
- 사용자에게 더 명확한 버튼 목적 제공

refactor(restaurantCard): 상세 정보 버튼 텍스트 수정

---

src/main/resources/static/js/currentLocationMain.js
src/main/resources/templates/mainPage.html

main page에서 사용자의 위치와의 거리 순으로 모든 음식점 출력 기능 구현

---

src/main/resources/static/css/owner-dashboard.css
src/main/resources/static/js/owner-inquiries.js
src/main/resources/templates/fragments/owner/inquiries.html
src/main/resources/templates/owner/dashboard.html

이 PR은 점주용 대시보드에 문의 관리 기능을 추가하고, 전반적인 UI/UX를 개선합니다.
1. 점주용 문의 내역 UI 구현
2. 문의 관리 기능 프론트엔드 구현
3. 점주 대시보드 및 문의 내역 페이지 스타일 개선
- `fragments/owner/inquiries.html`:
- 문의 내역 목록 테이블 추가
- 페이지네이션 UI 구현
- 문의 상세 보기 모달 추가
- 문의 삭제 확인 모달 추가
- 더미 데이터로 UI 구조 시각화
- owner-inquiries.js 스크립트 연결
- `owner-inquiries.js`:
- 문의 상세 보기 기능 구현
- 문의 삭제 기능 구현
- 문의 답변 저장 기능 구현
- 더미 데이터로 기능 테스트
- `dashboard.html`:
- owner-inquiries.js 스크립트 연결
- `owner-dashboard.css`:
- 전체 페이지 레이아웃 및 색상 스키마 최적화
- 사이드바 및 네비게이션 링크 스타일 개선
- 카드 및 버튼 디자인 일관성 강화
- 테이블 스타일 추가 및 가독성 개선
- 문의 내역 페이지를 위한 테이블, 버튼, 페이지네이션 스타일 구현
- 다크 모드 테마에 맞춘 전반적인 색상 조정
- #219
- #220
- #221
- 백엔드 API 연동 필요
이 PR은 프론트엔드 구현에 초점을 맞추고 있으며, 백엔드 연동은 향후 작업이 필요합니다.

(Uiux/owner) 점주용 문의 관리 기능 구현 및 UI 개선

---

src/main/java/com/whiskey/rvcom/misc/TestController.java
src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
src/main/resources/static/js/currentLocationMain.js
src/main/resources/static/js/kakaoMapDetailView.js
src/main/resources/templates/fragments/restaurantBanner.html
src/main/resources/templates/restaurantDetail.html

- 이름
- 카테고리
- 금일 영업시간 및 영업 여부
- 식당 전화번호, 주소
- 식당 위치 지도에 표시

음식점 상세 페이지에서 음식점의 정보를 받아와 표시

---

build/resources/main/templates/main.html
src/main/resources/static/js/restaurantDetail.js

Fix(report): 식당 상세보기 오류 해결 2 #241

---

src/main/resources/static/css/owner-dashboard.css
src/main/resources/templates/fragments/owner/notices.html

- 공지사항 관리 기능 구현
- 사이드바 및 전체 UI 개선
- 삭제 확인 모달 추가 및 삭제 로직 개선
1. 공지사항 관리
- 공지사항 목록, 작성, 삭제 기능 UI 구현
- 공지사항 카드 스타일 추가
- 삭제 확인 모달 구현으로 실수 방지
2. UI/UX 개선
- 사이드바 디자인 개선 (호버 효과, 활성 상태 스타일)
- 반응형 레이아웃 구현
- 다크 테마 스타일 일관성 개선
- 중복 코드 제거 및 스타일 정리
3. 성능 및 사용성 향상
- jQuery를 사용한 DOM 조작 및 이벤트 처리 최적화
- 반응형 디자인으로 다양한 디바이스 지원
이번 변경사항으로 점주 대시보드의 전반적인 사용자 경험과 디자인 일관성이 크게 개선되었습니다. 
공지사항 관리 기능 추가로 점주와 고객 간 효율적인 정보 전달이 가능해졌습니다.
- #239 공지사항 관리 기능 구현
- #245 사이드바 및 전체 UI 개선

(Uiux/owner) 점주 대시보드 개선 및 공지사항 기능 추가

---

src/main/java/com/whiskey/rvcom/review/ReviewController.java
src/main/resources/static/css/restaurantDetail.css
src/main/resources/templates/fragments/restaurantDetail/reviews.html
src/main/resources/templates/fragments/reviewItem.html

음식점 메인 평점 페이지 바인딩
리뷰댓글 및 리뷰카드 당 신고하기 버튼 스타일 적용

리뷰페이지 관련 추가 변경사항 패치

---

src/main/java/com/whiskey/rvcom/misc/TestController.java
src/main/java/com/whiskey/rvcom/repository/MenuRepository.java
src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
src/main/resources/static/css/restaurantDetail.css
src/main/resources/static/js/currentLocationMain.js
src/main/resources/templates/fragments/restaurantBanner.html
src/main/resources/templates/fragments/restaurantDetail/info.html
src/main/resources/templates/restaurantDetail.html

feat: 음식점 상세 페이지에서 음식점의 정보를 받아와 표시 기능 구현

---

.github/workflows/docker-image.yml
src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
src/main/java/com/whiskey/rvcom/businessregister/model/dto/BusinessRequestHead.java
src/main/java/com/whiskey/rvcom/businessregister/model/dto/ResponseBody.java
src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
src/main/resources/application.yml
src/main/resources/static/js/register-store.js
src/main/resources/templates/register-store.html

- 등록증번호, 개업일, 대표자명 입력 후 버튼 누르면 진위여부 확인

Feat(businessRegist): 입점신청 사용자등록증 진위여부 확인 #257

---

src/main/java/com/whiskey/rvcom/entity/review/Review.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewComment.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewImage.java

[긴급수정] 일부 엔티티 직렬화 시도 시 순환참조 발생하는 양방향 관계 엔티티 일부 수정

---

src/main/resources/static/css/mainPage.css
src/main/resources/static/js/currentLocationMain.js
src/main/resources/templates/fragments/banner.html
src/main/resources/templates/mainPage.html

- 현재 위치 로딩 애니메이션 및 오류 처리 개선
- 스켈레톤 UI 및 레스토랑 카드 애니메이션 효과 추가
- 메인 페이지 UI 요소 정리 및 최적화
- 위치 정보 로딩 중 애니메이션 UI 추가
- 위치 정보 가져오기 실패 시 사용자 친화적 오류 메시지 표시
- CSS 스타일 추가로 로딩 애니메이션 및 위치 텍스트 스타일링
- HTML 구조 업데이트로 새로운 UI 요소 통합
- 스켈레톤 UI 추가로 로딩 시 시각적 피드백 제공
- 레스토랑 카드에 팝인 및 호버 애니메이션 효과 적용
- 비동기 로딩으로 레스토랑 카드 순차적 표시
- 에러 처리 개선 및 사용자 친화적 메시지 추가
- 상세 정보 버튼 텍스트 변경 ("상세 정보 / 주문" -> "상세 정보")
- 카드 표시 애니메이션 간격 조정 (200ms -> 100ms)
- 불필요한 TODO 주석 및 푸터 관련 주석 제거
- 다양한 브라우저 및 디바이스에서 UI 호환성 확인
- 위치 정보 로딩 및 오류 상황에 대한 사용자 경험 테스트
- 레스토랑 카드 로딩 애니메이션 성능 확인
이 PR을 통해 메인 페이지의 전반적인 사용자 경험이 크게 개선될 것으로 기대됩니다. 리뷰 및 피드백 부탁드립니다.

[uiux/refactor] 메인 페이지 UI/UX 개선 및 위치 기반 기능 강화

---

src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
src/main/java/com/whiskey/rvcom/businessregister/model/dto/MyResponseBody.java
src/main/java/com/whiskey/rvcom/businessregister/model/dto/RegistInfo.java
src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
src/main/resources/static/js/register-store.js
src/main/resources/templates/admin/registrestaurant.html
src/main/resources/templates/register-store.html

- 진위확인 후 수기등록하면 SUBMITTED 상태로 등록됩니다.

Feat(businessRegist): 입점신청 등록 프로세스 완료 #273

---

src/main/resources/templates/admin/adminMain.html

Feat(businessRegist): 입점신청 목록 전체 조회 2 #275

---

src/main/resources/templates/admin/registrestaurant.html

Fix(businessRegist): 입점신청 목록 전체 조회 오류 해결 #280

---

src/main/java/com/whiskey/rvcom/entity/review/Review.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewLike.java
src/main/resources/static/js/admin/review-report.js
src/main/resources/templates/admin/fragments/report-management.html
src/main/resources/templates/report/reviewreport.html

Fix(report): 리뷰 신고 목록 조회 매핑 문제 해결 #283

---

src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java

Fix(report) 리뷰, 댓글 신고 처벌 결정에 따른 상태값 변경 메서드

---

src/main/java/com/whiskey/rvcom/misc/TestController.java
src/main/java/com/whiskey/rvcom/repository/RestaurantRepository.java
src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantViewController.java
src/main/java/com/whiskey/rvcom/restaurant/controller/restaurantController.java
src/main/java/com/whiskey/rvcom/restaurant/dto/RestaurantSearchResultDTO.java
src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
src/main/resources/static/js/kakaoMapSearchResultView.js
src/main/resources/static/js/kakaoMapView.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/resultCard.html
src/main/resources/templates/searchResults.html

- 음식점 목록에서 음식점 div hover 되는 경우, 지도의 음식점 위치에 marker가 변경된다.
- 지도에서 음식점의 마커에 hover 되는 경우, 지도의 해당 음식점이 강조된다.

검색 시 검색 내용에 연관된 음식점 표시

---

src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java
src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
src/main/resources/templates/admin/regist-detail.html
src/main/resources/templates/admin/registrestaurant.html
src/main/resources/templates/report/reviewcommentreport.html

입점 프로세스 : 세부조회, 처리기능

---

src/main/resources/static/css/restaurantDetail.css
src/main/resources/static/css/restaurantDetail/reviews.css
src/main/resources/static/js/restaurantDetail.js
src/main/resources/templates/fragments/restaurantDetail/info.html
src/main/resources/templates/fragments/reviewItem.html
src/main/resources/templates/restaurantDetail.html

- 리뷰 및 댓글에 대한 신고 기능 추가 (연동 대기중)
- 신고 버튼 UI 개선 및 아이콘 추가
- 신고 모달 창 디자인 개선
- 전반적인 UI 일관성 향상 및 반응형 디자인 적용
- JavaScript 코드 정리 및 가독성 개선
- `restaurantDetail.js`에 리뷰 및 댓글 신고 기능 구현 예정 @l2chmnl 
- `reviewItem.html`에 신고 버튼 UI 추가
- `restaurantDetail.html`에 신고 모달 추가
- `reviews.css`에 신고 버튼 스타일 추가
- 신고 버튼 디자인 개선 (눈에 띄는 색상, 아이콘 추가, 호버 효과)
- 모달 창 스타일 개선 (패딩, 그림자, 폰트 크기 등)
- 폼 요소 스타일 개선 (입력 필드, 버튼 등)
- 반응형 디자인 적용
- JavaScript 코드 포맷팅 및 구조 개선
- 신고 폼 레이아웃 및 라벨 정리
Closes #285
- 백엔드 API 엔드포인트 구현 필요

[ui/ux] 음식점 상세 페이지 신고 기능 개선 및 UI/UX 리팩토링

---

src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
src/main/java/com/whiskey/rvcom/inquiry/dto/RestaurantInquiryResponseDTO.java
src/main/resources/static/js/restaurantDetail/inquiries.js
src/main/resources/templates/fragments/inquiryItem.html

- 문의 삭제 버튼 추가해서 문의 삭제하도록 기능 구현과 web연동
- 문의 조회 로직 개선
- 문의 조회시 최근 날짜순으로 정렬

문의 삭제 기능 web 연동과 문의 조회 부분 수정

---

src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
src/main/java/com/whiskey/rvcom/notice/dto/RestaurantNoticeResponseDTO.java
src/main/resources/templates/fragments/restaurantDetail/notices.html

- 공지사항 식별을 위한 id 필드와 삭제 여부를 확인하기 위해 isDeleted 필드 추가
- 필드 변경으로 인한 객체값도 변경하여 매핑
- 추가로 사용자페이지에서 공지사항 작성 버튼 안보이도록 설정

refactor:  DTO에 id와 삭제여부 필드 추가 및 매핑 업데이트

---

src/main/resources/static/css/admin/admin-dashboard.css
src/main/resources/static/js/admin/comment-report.js
src/main/resources/static/js/admin/restaurant-report.js
src/main/resources/static/js/admin/review-report.js
src/main/resources/templates/admin/fragments/report-management.html

- 신고 처리 UI 개선 및 기능 강화
- 신고 관리 페이지의 반응형 디자인 적용
- 신고 목록 및 상세 정보 표시 개선
- 신고 처리 상태 UI 업데이트 로직 추가
- 에러 처리 및 로깅 개선
- 테이블 구조 개선
- 신고 관리를 위한 새로운 스타일 추가
- 카드, 테이블, 상태 표시 등의 디자인 개선
- 페이지네이션 UI 개선
- 반응형 디자인 적용
- 중복 코드 제거 및 코드 재사용성 향상
- 명확한 변수명과 함수명 사용으로 가독성 개선
1. 각 신고 유형(식당, 리뷰, 댓글)별 목록 표시 확인
2. 신고 상세 정보 표시 기능 확인
3. 신고 처리 상태 변경 및 UI 업데이트 확인
4. 반응형 디자인 동작 확인 (다양한 화면 크기에서 테스트)
5. 에러 상황에서의 UI 및 로깅 동작 확인
- 백엔드 API와의 연동 확인 및 필요시 조정
- 성능 최적화 (대량의 신고 데이터 처리 시 성능 확인)
- 접근성 개선을 위한 추가 작업 검토
이 PR을 통해 관리자의 신고 관리 업무 효율성이 크게 향상될 것으로 기대됩니다. 리뷰 후 피드백 주시면 감사하겠습니다.

feat(admin): 신고 처리 UI 개선 및 기능 강화 

---

src/main/java/com/whiskey/rvcom/controller/AdminController.java
src/main/resources/static/js/admin/admin-dashboard.js
src/main/resources/static/js/admin/restaurant-management.js
src/main/resources/templates/admin/adminMain.html
src/main/resources/templates/admin/fragments/restaurant-management.html

- 관리자 대시보드에 입점 관리 탭 추가
- 입점 신청 목록 조회 및 표시 기능 구현
- 페이지네이션 구현
- 승인, 거절, 상세보기 기능을 위한 기본 구조 추가
- `AdminController.java`: 입점 관리 페이지 요청 처리를 위한 새 엔드포인트 추가
- `admin-dashboard.js`: 입점 관리 탭 관련 로직 추가
- `restaurant-management.js`: 입점 신청 관리 기능 구현
- `adminMain.html`: 입점 관리 탭 및 관련 스크립트 추가
- `restaurant-management.html`: 입점 신청 목록 표시 UI 구현
1. 관리자 페이지에 접속
2. 좌측 메뉴에서 '입점 관리' 탭 선택
3. 입점 신청 목록이 정상적으로 표시되는지 확인
4. 페이지네이션 동작 확인
5. 승인, 거절, 상세보기 버튼 클릭 시 콘솔에 로그가 출력되는지 확인
Closes #258

feat(admin): 관리자 페이지 입점 관리 기능 추가 (#258)

---

src/main/resources/templates/fragments/reviewItem.html

뷰 id 바인딩 문법 오류 긴급수정

---

src/main/java/com/whiskey/rvcom/repository/ReviewLikeRepository.java
src/main/java/com/whiskey/rvcom/review/ReviewController.java
src/main/java/com/whiskey/rvcom/review/ReviewLikeService.java
src/main/resources/static/js/restaurantDetail/reviews.js
src/main/resources/templates/fragments/reviewItem.html

- 동휘님 외에 merge는 하지 말아주세요!
- 다른 분들은 review 후 approve만 부탁드립니다!
- 동휘님 외에 merge는 하지 말아주세요!
- 다른 분들은 review 후 approve만 부탁드립니다!
- 동휘님 외에 merge는 하지 말아주세요!
- 다른 분들은 review 후 approve만 부탁드립니다!

Feat(ReviewLike): 리뷰 좋아요 기능 구현 #303

---

src/main/resources/static/js/restaurantDetail/reviews.js

Fix(report): 댓글 작성 후 신고하기 버튼이 달라지는 현상 해결 #305

---

src/main/resources/static/css/admin/admin-dashboard.css
src/main/resources/static/css/common.css
src/main/resources/static/css/writeReview.css
src/main/resources/static/js/admin/restaurant-management.js
src/main/resources/static/js/admin/restaurant-report.js
src/main/resources/templates/admin/fragments/report-management.html

- 리뷰 작성 페이지 UI 개선 및 반응형 디자인 적용
- 식당 신고 관리 기능 개선 및 정렬 기능 추가
- CSS 변수 및 기본 설정 추가로 일관된 디자인 구현
- 반응형 디자인 적용으로 모바일 사용성 개선
- 접근성 스타일 추가로 웹 표준 준수
- 다중 필드 정렬 기능 추가 (날짜, 상태 기준)
- 테이블 렌더링 로직 개선 및 모듈화
- 에러 처리 강화 및 사용자 피드백 개선
1. 리뷰 작성 페이지 반응형 디자인 테스트 (다양한 디바이스)
2. 식당 신고 목록 정렬 기능 테스트
3. 에러 상황에서의 사용자 피드백 확인

[Uiux/refactor] 리뷰 작성 페이지 UI 개선 및 식당 신고 관리 기능 강화

---

src/main/resources/templates/login.html
src/main/resources/templates/register_basic.html
src/main/resources/templates/register_social.html

-로그인뷰에서 충돌 부분 해결 및 로고 삽입 완료 했습니다
-회원가입단도 로고 부분 삽입완료 했습니다.

edit: 로그인, 회원가입 뷰단 로고 삽입

---

src/main/resources/templates/fragments/header.html

주요 변경사항:
1. 로고 디자인 개선
- 이미지와 텍스트를 포함한 새로운 로고 구조 추가
- 로고 링크에 클래스 추가 및 인라인 스타일 제거
2. 불필요한 코드 제거
- 주석 처리된 검색바 관련 코드 제거
- 중복된 헤더 구조 코드 제거
3. 코드 구조 개선
- 헤더 마크업 구조 간소화
테스트:
추가 고려사항:
- 새로운 로고 디자인이 다양한 화면 크기에서 잘 표시되는지 확인해주세요.

Uiux/refactor: 로고 추가 및 불필요한 코드 제거

---

src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
src/main/resources/static/css/mypage.css
src/main/resources/static/js/mypage.js
src/main/resources/templates/fragments/mypage_sidebar.html
src/main/resources/templates/mypage.html

-표시되는 변수 말고도 로직상에서도 bookmark->favorite으로 변경

edit: bookmark -> favorite으로 변경됨

---

src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java

Refactor(report): 메일 발송 멘트 수정 #347

---

src/main/resources/static/css/admin/admin-dashboard.css
src/main/resources/static/js/admin/restaurant-management.js
src/main/resources/templates/admin/adminMain.html
src/main/resources/templates/admin/fragments/restaurant-management.html

- 관리자 대시보드의 색상 테마 변경 (#4fc3f7 → #00cba6)
- 레스토랑 관리 페이지에 상세보기 모달 추가
- 레스토랑 승인/거절 프로세스 개선
- 전체적인 색상 테마 변경으로 시각적 일관성 향상
- 모달 스타일 개선 및 반응형 디자인 적용
- 상세보기 기능 구현 (AJAX를 통한 데이터 로드)
- 승인 및 거절 기능 로직 개선
- 모달 관련 기능 추가 (열기, 닫기)
- adminMain.html: 불필요한 '입점 신청 관리' 버튼 제거
- restaurant-management.html: 상세보기 모달 추가
- 관리자 대시보드의 사용자 경험 개선
- 레스토랑 관리 프로세스의 효율성 향상
- 상세 정보 확인을 통한 더 나은 의사 결정 지원
- 새로운 색상 테마의 가독성 및 사용성 확인
- 상세보기 모달의 정상 작동 여부
- 승인/거절 프로세스의 정확성 검증

style(admin): 관리자 대시보드 UI 개선 및 레스토랑 관리 기능 강화

---

src/main/java/com/whiskey/rvcom/entity/restaurant/Restaurant.java
src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java

fix: Restaurant.menus와 Menu.restaurant 사이에서 발생하는 순환참조 문제 해결

---

src/main/java/com/whiskey/rvcom/businessregister/controller/BusinessRegisterController.java
src/main/java/com/whiskey/rvcom/businessregister/service/BusinessRegisterService.java

- 현재 Restaurant의 Address는 위도 경도 0.0으로 삽입됩니다.

Feat(business): 입점신청 승인 후 레스토랑 등록 기능 #355

---

src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java

음식점 주간 영업시간이 null인 경우 발생하는 null exception 예외 처리 완료

HotFix : weekly_open_close_time NULL EXCEPTION

---

src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
src/main/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyRestController.java
src/main/java/com/whiskey/rvcom/inquiry/reply/RestaurantInquiryReplyService.java
src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
src/main/java/com/whiskey/rvcom/notice/RestaurantOwnerNoticeController.java
src/main/java/com/whiskey/rvcom/repository/RestaurantNoticeRepository.java
src/main/resources/static/js/owner/inquiries.js
src/main/resources/static/js/owner/notices.js
src/main/resources/templates/fragments/owner/inquiries.html
src/main/resources/templates/fragments/owner/notices.html

- 추가로 피드백 주셨던 닫기, 취소 버튼 제거했습니다.

공지사항 및 문의내역 페이지네이션 오류 해결

---

src/main/java/com/whiskey/rvcom/report/controller/CommentReportController.java
src/main/java/com/whiskey/rvcom/report/controller/RestaurantReportController.java
src/main/java/com/whiskey/rvcom/report/controller/ReviewReportController.java
src/main/java/com/whiskey/rvcom/report/service/RestaurantReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewCommentReportService.java
src/main/java/com/whiskey/rvcom/report/service/ReviewReportService.java
src/main/java/com/whiskey/rvcom/repository/ReviewCommentReportRepository.java

Refactor(report): 모든 신고 처리전 조회로 변경

---

src/main/java/com/whiskey/rvcom/entity/review/Review.java
src/main/java/com/whiskey/rvcom/restaurant/controller/restaurantController.java
src/main/resources/templates/fragments/restaurantDetail/reviews.html
src/main/resources/templates/fragments/reviewItem.html

- Review 엔티티 구조 변경
- 데이터베이스 내 칼럼 추가
- [이슈]이미지 바인딩 시 라운딩처리되지 않는 이슈 - 업요예정 @kebin0591

리뷰페이지 관련 내용 바인딩 추가

---

src/main/java/com/whiskey/rvcom/entity/restaurant/menu/Menu.java
src/main/java/com/whiskey/rvcom/restaurant/controller/RestaurantMenuController.java
src/main/java/com/whiskey/rvcom/restaurant/service/MenuService.java
src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
src/main/resources/static/js/menu-management.js

- 음식점 삭제 시 해당 음식점이 페이지의 유일한 메뉴일 때, reloading이 안되는 문제 발생 (추후 해결 예정)

feat: 점주 페이지에서 음식점 메뉴 추가, 수정, 삭제 기능 구현

---

src/main/resources/static/js/admin/review-report.js
src/main/resources/templates/admin/fragments/report-management.html

Refactor(report): 엔티티 변경에 수정사항 수정 #374

---

src/main/resources/static/css/common.css
src/main/resources/static/css/mainPage.css

1. 컨테이너 패딩 조정:
- .container 클래스의 좌우 패딩을 0px에서 20px로 변경
- 페이지 콘텐츠의 가독성과 레이아웃 향상
2. 이미지 스타일 개선:
- .img-fluid 클래스에 border-radius: 8px 추가
- 유동적 이미지의 모서리를 둥글게 처리하여 시각적 일관성 향상

Uiux/refactor 공통 스타일 개선: 컨테이너 패딩 및 이미지 스타일 조정

---

src/main/resources/static/js/owner/inquiries.js
src/main/resources/static/js/owner/notices.js

- 추가로 ajax 설정값들 일관성있게 순서 정리 및 수정

음식점ID 동적으로 받아서 처리하도록 로직 개선

---

src/main/resources/static/css/admin/admin-dashboard.css
src/main/resources/static/js/admin/admin-dashboard.js
src/main/resources/templates/admin/adminMain.html
src/main/resources/templates/admin/fragments/dashboard.html

1. 반응형 디자인 개선 및 모바일 사용성 향상
2. 상단 바 UI 개선 및 빠른 액세스 메뉴 추가
3. FoodFolio 로고 기능 개선 및 UI 상호작용 강화
4. 빠른 링크 버튼 스타일 개선 및 이벤트 처리 최적화
5. 전체적인 색상 체계 및 가독성 개선
- CSS:
- 반응형 레이아웃 및 요소 스타일 최적화
- 사이드바 동작 개선 및 토글 버튼 추가
- 상단 바, 드롭다운 메뉴, 로고 등의 스타일 개선
- 주요 색상을 #00e88f에서 #00cba6로 변경
- JavaScript:
- 사이드바 토글 기능 구현
- 빠른 액세스 메뉴 및 로고 클릭 이벤트 처리
- 화면 크기에 따른 UI 요소 표시 로직 추가
- 디버깅을 위한 로깅 추가
- HTML:
- 사이드바 토글 버튼 마크업 추가
- 빠른 액세스 드롭다운 메뉴 추가
- FoodFolio 로고에 id 속성 추가
이번 변경으로 관리자 대시보드의 전반적인 사용성과 시각적 매력이 크게 향상되었습니다. 특히 모바일 환경에서의 사용성이 개선되어 다양한 디바이스에서 일관된 경험을 제공할 수 있게 되었습니다. 또한, 디버깅 및 유지보수가 용이해져 향후 개발 및 운영 효율성이 증대될 것으로 기대됩니다.

(Uiux/refactor) 관리자 대시보드 UI/UX 전면 개선 및 모바일 대응 강화

---

src/main/java/com/whiskey/rvcom/restaurant/dto/RestaurantSearchResultDTO.java
src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
src/main/resources/templates/fragments/resultCard.html
src/main/resources/templates/searchResults.html

service 및 컨트롤러, 그리고 바인딩되는 dto구조 일부 변경하였습니다. 
병합간 참고해주시기 바랍니다.
---
1. 이미지 바인딩 추가
2. 별점 바인딩 추가
3. 대표 리뷰(별점 1위 리뷰 내용 바인딩)
4. 음식점 제목에서 번호 제거

feat: 음식점 검색페이지 필요 정보 추가 바인딩

---

src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
src/main/resources/static/js/mypage.js
src/main/resources/static/js/register.js
src/main/resources/templates/fragments/mypage_profileHeader.html
src/main/resources/templates/mypage.html
src/main/resources/templates/register_basic.html

-일반회원가입시 로그인ID부터 체크하게 알럿을통해 유도
-즐겨찾기 해제시 페이징 오류 해결

Edit: 일반 회원가입시 알럿추가 및 즐겨찾기 해제 로직 수정

---

src/main/resources/static/css/header.css
src/main/resources/static/css/login.css
src/main/resources/static/css/owner-dashboard.css
src/main/resources/static/css/register.css
src/main/resources/static/js/owner-dashboard.js
src/main/resources/static/js/owner/inquiries.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/owner/dashboard.html
src/main/resources/templates/fragments/owner/inquiries.html
src/main/resources/templates/fragments/owner/menu-management.html
src/main/resources/templates/fragments/owner/notices.html
src/main/resources/templates/fragments/restaurantDetail/info.html
src/main/resources/templates/owner/dashboard.html
src/main/resources/templates/restaurantDetail.html

- 헤더, 로그인/회원가입 페이지, 오너 대시보드, 레스토랑 상세 페이지의 UI/UX 개선
- 반응형 디자인 구현 및 강화
- 코드 리팩토링 및 기능 개선
- 네비게이션 버튼 스타일 개선 (배경색, 테두리 반경, 호버 효과 등)
- 아이콘 추가 및 정렬
- 반응형 디자인 로직 개선 (미디어 쿼리 수정)
- 로고 이미지 크기 조정 (최대 높이 380px에서 250px로 감소)
- UI/UX 개선 및 반응형 디자인 구현
- 사이드바 토글 기능 추가
- 빠른 링크 섹션 UI 개선 및 기능 구현
- 드롭다운 메뉴 스타일 개선
- 로고 클릭 시 대시보드로 이동 기능 추가
- 문의 내역 UI 개선 및 반응형 디자인 구현
- 메뉴 섹션 및 식당 정보 UI 개선
- '인기 메뉴' 제목을 '메뉴'로 변경
- '전체 메뉴 보기' 버튼 제거
- 홈페이지 정보 제거
1. 다양한 화면 크기에서 반응형 디자인 테스트
2. 오너 대시보드의 모든 기능 (사이드바 토글, 빠른 링크 등) 테스트
3. 헤더의 네비게이션 및 아이콘 동작 확인
4. 로그인/회원가입 페이지의 로고 크기 적절성 확인
5. 레스토랑 상세 페이지의 UI 변경 사항 확인
- 브라우저 호환성 확인 필요
- 성능 영향 평가 (특히 CSS 변경으로 인한 렌더링 성능)
- 사용자 피드백 수집 계획 수립

Uiux/refactor 피드백 수용 및 UI/UX 개선 및 반응형 디자인 개선

---

src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeController.java
src/main/resources/static/js/restaurantDetail/notices.js
src/main/resources/templates/fragments/owner/notices.html
src/main/resources/templates/fragments/restaurantDetail/notices.html

사용자 페이지 공지사항 조회 코드 간결화

---

src/main/resources/static/js/owner/inquiries.js
src/main/resources/static/js/owner/notices.js
src/main/resources/templates/fragments/owner/inquiries.html

- 전체적으로 코드 정리했고 기능별 주석 간단하게 추가했습니다.
- 추가로 공지사항 삭제 시 alert창이 2번 뜨는 문제 해결했습니다.

점주 페이지 문의 내역, 공지사항 코드 정리

---

src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
src/main/java/com/whiskey/rvcom/Member/service/MemberManagementService.java
src/main/java/com/whiskey/rvcom/Member/service/SocialLoginService.java
src/main/java/com/whiskey/rvcom/config/SecurityConfig.java
src/main/java/com/whiskey/rvcom/controller/AdminController.java
src/main/java/com/whiskey/rvcom/misc/TestController.java
src/main/java/com/whiskey/rvcom/repository/MemberRepository.java
src/main/resources/static/js/admin/user-management.js
src/main/resources/templates/admin/adminMain.html
src/main/resources/templates/admin/fragments/user-management.html

- 관리자 페이지에서 회원정보 가져오기 및 페이지네이션 적용
- 회원정보 조회 부분에서 테이블 디자인 수정필요 -@kebin0591  
- Admincontroller에서 중복되는 내용 주석 및 관리자이름및 프로필 사진 로그아웃 구현중 -이메일 인증 주소 변경 -@kebin0591  이작업도 넘겨도 될까요...

feat: 관리자페이지: 회원정보 조회 및 페이지네이션,

---

src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java

-회원가입부분에서 컨트롤러에서 중복으로 이메일인증을 처리하고 있었습니다 주석처리하였습니다

edit: 회원가입 수정

---

src/main/resources/static/js/mypage.js

-http와 https 상태에서도 둘다 즐겨찾기가 되도록 수정했습니다.
-Mixed Content 오류 해결

edit: js 서버환경에서 적용되게끔 변경

---

src/main/java/com/whiskey/rvcom/controller/OwnerFragmentController.java
src/main/resources/static/js/owner-dashboard.js
src/main/resources/templates/fragments/owner/dashboard.html
src/main/resources/templates/owner/dashboard.html

- OwnerFragmentController: 미답변 문의 카운트 로직 추가
- owner-dashboard.js:
- 미답변 문의 카운트 업데이트 함수 구현
- 대시보드 초기화 시 미답변 문의 카운트 업데이트 로직 추가
- dashboard.html: 미답변 문의 카운트 표시 방식 변경

feat(owner-dashboard): 미답변 문의 카운트 기능 추가 및 대시보드 개선

---

src/main/resources/application.yml
src/main/resources/templates/fragments/mypage_contentSection.html
src/main/resources/templates/register_social.html

-직접 메인 배포서버의 https 주소를 넣어주게 되어 구글 로그인 api정책을 지키면서 작동하게끔 변경하였습니다

feat: redirect-uri 추가

---

src/main/java/com/whiskey/rvcom/ImageFile/ImageFileService.java
src/main/java/com/whiskey/rvcom/controller/OwnerFragmentController.java
src/main/java/com/whiskey/rvcom/entity/review/ReviewImage.java
src/main/java/com/whiskey/rvcom/restaurant/controller/restaurantController.java
src/main/java/com/whiskey/rvcom/restaurant/service/RestaurantService.java
src/main/java/com/whiskey/rvcom/review/ReviewController.java
src/main/java/com/whiskey/rvcom/review/ReviewService.java
src/main/resources/static/css/writeReview.css
src/main/resources/static/js/restaurantDetail/reviews.js
src/main/resources/templates/fragments/photoUpload.html
src/main/resources/templates/fragments/reviewItem.html
src/main/resources/templates/fragments/reviewSubmitButtons.html
src/main/resources/templates/fragments/reviewTextarea.html
src/main/resources/templates/fragments/starRating.html
src/main/resources/templates/receiptVerification.html
src/main/resources/templates/writeReview.html

1. 영수증인증 프로세스 내 라이브 카메라를 통한 촬영으로도 인증이 가능하도록 수정
2. 리뷰 작성 페이지 UI 개선(기존 ui 복원)
3. 리뷰 작성 완료 후 이미지 등록되지 않는 문제 수정
4. 음식점 별 평점(실수값)을 소수점 1자리까지 표시되도록 수정
5. 리뷰 좋아요 요청 넘어가지 않는 문제 수정
6. 리뷰 페이지 내 노출되는 리뷰 카드의 노출 순서를 작성순(최근순)으로 노출되도록 수정

리뷰관련 로직 개선

---

src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryRestController.java
src/main/java/com/whiskey/rvcom/inquiry/RestaurantInquiryService.java
src/main/java/com/whiskey/rvcom/notice/RestaurantNoticeService.java
src/main/java/com/whiskey/rvcom/notice/RestaurantOwnerNoticeController.java

- 사용자가 명확하게 구분되도록 controller의 메서드명 변경
- 매개변수 순서를 변경하여 코드 일관성 및 가독성 향상
- 사용하지 않는 메서드 및 주석 삭제

refactor: 코드 일관성 및 가독성 향상을 위한 리팩토링

---

src/main/resources/static/js/admin/restaurant-management.js

- 레스토랑 테이블 렌더링 함수에서 '승인' 및 '거절' 버튼 제거
- '상세보기' 버튼만 유지하여 UI 간소화 및 사용자 경험 개선
- 레스토랑 상태 관리 로직 변경 예상, 상세 보기에서 처리할 것으로 추정

uiux/refactor(restaurant-management): 레스토랑 관리 UI 간소화

---

src/main/resources/templates/admin/adminMain.html
src/main/resources/templates/fragments/owner/menu-management.html

- 관리자 드롭다운 메뉴에 '메인 화면' 항목 추가
- 홈 아이콘을 사용하여 시각적 구분 제공
- 루트 경로('/')로 이동하는 링크 설정

feat(adminMain): 관리자 메뉴에 메인 화면 링크 추가

---

src/main/java/com/whiskey/rvcom/Member/controller/MemberController.java
src/main/resources/templates/fragments/mypage_contentSection.html
src/main/resources/templates/mypage.html

-회원 탈퇴 부분 수정 알럿이 뜰수 있도록
-마이페이지에서 리뷰가 별이 5개인 경우 별이 7개 나오는 버그 해결

edit: 회원 탈퇴 부분 및 리뷰 별버그 해결
